name: notezy
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8

  # state management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^15.1.2

  # core
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_auth: ^5.6.1

  # storage
  shared_preferences: ^2.5.3

  # code generation
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_serializable: ^6.9.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^6.0.0
  riverpod_lint: ^2.6.5

  # code generation
  build_runner: ^2.4.15
  go_router_builder: ^2.9.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  uses-material-design: true
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_italic.ttf
          style: italic
        - asset: assets/fonts/poppins_black_italic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/